const groupPairToCityEntries: Array<[[string, string], string]> = [
  [["Afrique du Sud", "Corée du Sud"], "Monterrey"],
  [["Afrique du Sud", "Tchéquie"], "Atlanta"],
  [["Allemagne", "Côte d'Ivoire"], "Toronto"],
  [["Allemagne", "Curaçao"], "Houston"],
  [["Allemagne", "Équateur"], "Toronto"],
  [["Algérie", "Argentine"], "Kansas City"],
  [["Algérie", "Autriche"], "Kansas City"],
  [["Arabie Saoudite", "Cabo Verde"], "Houston"],
  [["Arabie Saoudite", "Espagne"], "Atlanta"],
  [["Arabie Saoudite", "Uruguay"], "Miami"],
  [["Argentine", "Autriche"], "Dallas"],
  [["Argentine", "Jordanie"], "Dallas"],
  [["Australie", "Paraguay"], "San Francisco Bay Area"],
  [["Australie", "Türkiye"], "San Francisco Bay Area"],
  [["Belgique", "Égypte"], "Seattle"],
  [["Belgique", "Iran"], "Los Angeles"],
  [["Belgique", "Nouvelle-Zélande"], "Vancouver"],
  [["Bosnie-Herzégovine", "Canada"], "Toronto"],
  [["Bosnie-Herzégovine", "Qatar"], "Seattle"],
  [["Bosnie-Herzégovine", "Suisse"], "Seattle"],
  [["Brésil", "Écosse"], "Boston"],
  [["Brésil", "Haïti"], "Philadelphia"],
  [["Brésil", "Maroc"], "New Jersey"],
  [["Cabo Verde", "Espagne"], "Atlanta"],
  [["Cabo Verde", "Uruguay"], "Miami"],
  [["Canada", "Qatar"], "Vancouver"],
  [["Canada", "Suisse"], "Vancouver"],
  [["Congo DR", "Colombie"], "Guadalajara"],
  [["Congo DR", "Ouzbékistan"], "Atlanta"],
  [["Corée du Sud", "Mexique"], "Guadalajara"],
  [["Côte d'Ivoire", "Curaçao"], "Philadelphia"],
  [["Côte d'Ivoire", "Équateur"], "Philadelphia"],
  [["Croatie", "Angleterre"], "Dallas"],
  [["Croatie", "Ghana"], "Philadelphia"],
  [["Curaçao", "Équateur"], "Kansas City"],
  [["Égypte", "Iran"], "Seattle"],
  [["Égypte", "Nouvelle-Zélande"], "Vancouver"],
  [["Écosse", "Haïti"], "Boston"],
  [["Écosse", "Maroc"], "Boston"],
  [["Espagne", "Cabo Verde"], "Atlanta"],
  [["Espagne", "Uruguay"], "Miami"],
  [["France", "Irak"], "Philadelphia"],
  [["France", "Norvège"], "Boston"],
  [["France", "Sénégal"], "New Jersey"],
  [["Ghana", "Panama"], "Toronto"],
  [["Haïti", "Écosse"], "Boston"],
  [["Haïti", "Maroc"], "Atlanta"],
  [["Irak", "Norvège"], "Boston"],
  [["Irak", "Sénégal"], "Toronto"],
  [["Iran", "Nouvelle-Zélande"], "Los Angeles"],
  [["Japon", "Pays-Bas"], "Dallas"],
  [["Japon", "Suède"], "Monterrey"],
  [["Japon", "Tunisie"], "Monterrey"],
  [["Jordanie", "Algérie"], "San Francisco Bay Area"],
  [["Jordanie", "Autriche"], "San Francisco Bay Area"],
  [["Mexique", "Afrique du Sud"], "Mexico City"],
  [["Mexique", "Corée du Sud"], "Guadalajara"],
  [["Mexique", "Tchéquie"], "Mexico City"],
  [["Nouvelle-Zélande", "Égypte"], "Vancouver"],
  [["Nouvelle-Zélande", "Iran"], "Los Angeles"],
  [["Norvège", "Sénégal"], "New Jersey"],
  [["Ouzbékistan", "Colombie"], "Guadalajara"],
  [["Ouzbékistan", "Portugal"], "Houston"],
  [["Pays-Bas", "Suède"], "Houston"],
  [["Pays-Bas", "Tunisie"], "Kansas City"],
  [["Panama", "Angleterre"], "New Jersey"],
  [["Panama", "Croatie"], "Toronto"],
  [["Paraguay", "Australie"], "San Francisco Bay Area"],
  [["Paraguay", "USA"], "Los Angeles"],
  [["Portugal", "Colombie"], "Houston"],
  [["Portugal", "Congo DR"], "Houston"],
  [["Portugal", "Ouzbékistan"], "Houston"],
  [["Qatar", "Suisse"], "San Francisco Bay Area"],
  [["Sénégal", "Norvège"], "New Jersey"],
  [["Suède", "Tunisie"], "Monterrey"],
  [["Türkiye", "Paraguay"], "San Francisco Bay Area"],
  [["Türkiye", "USA"], "Los Angeles"],
  [["Tunisie", "Japon"], "Monterrey"],
  [["USA", "Australie"], "Seattle"],
  [["Uruguay", "Cabo Verde"], "Miami"],
  [["Uruguay", "Espagne"], "Guadalajara"],
];

function pairKey(teamA: string, teamB: string) {
  return [teamA, teamB].sort((left, right) => left.localeCompare(right)).join("|");
}

const groupPairToCity = new Map(
  groupPairToCityEntries.map(([[teamA, teamB], city]) => [pairKey(teamA, teamB), city])
);

export const FIFA_TEAMS = Array.from(
  new Set(groupPairToCityEntries.flatMap(([[teamA, teamB]]) => [teamA, teamB]))
).sort((left, right) => left.localeCompare(right));

export function getGroupMatchCity(teamA?: string, teamB?: string) {
  if (!teamA || !teamB) return null;
  return groupPairToCity.get(pairKey(teamA, teamB)) ?? null;
}