export const topScorerCandidates = [
  "Kylian Mbappe",
  "Michael Olise",
  "Harry Kane",
  "Mikel Oyarzabal",
  "Erling Haaland",
  "Lionel Messi",
  "Lamine Yamal",
  "Cristiano Ronaldo",
  "Julian Alvarez",
  "Vinicius Jr",
  "Raphinha",
  "Kai Havertz",
  "Lautaro Martinez",
  "Bukayo Saka",
  "Jamal Musiala",
  "Florian Wirtz",
  "Jude Bellingham",
  "Cody Gakpo",
  "Memphis Depay",
  "Robert Lewandowski",
  "Alvaro Morata",
  "Nico Williams",
  "Rafael Leao",
  "Bruno Fernandes",
  "Khvicha Kvaratskhelia",
  "Son Heung-min",
  "Mohamed Salah",
  "Sadio Mane",
  "Youssef En-Nesyri",
  "Christian Pulisic",
  "Tim Weah",
  "Giovanni Reyna",
  "Ricardo Pepi",
  "Luis Diaz",
  "James Rodriguez",
  "Darwin Nunez",
  "Federico Valverde",
  "Nicolas Jackson",
  "Serhou Guirassy",
  "Victor Osimhen",
  "Victor Boniface",
  "Ibrahim Diaz",
  "Cole Palmer",
  "Phil Foden",
  "Ollie Watkins",
  "Marcus Rashford",
  "Gabriel Jesus",
  "Rodrygo",
  "Endrick",
  "Rasmus Hojlund",
  "Andreas Skov Olsen",
  "Goncalo Ramos",
  "Diogo Jota",
  "Pedro Neto",
  "Joao Felix",
  "Romelu Lukaku",
  "Leandro Trossard",
  "Jeremy Doku",
  "Alexander Isak",
  "Viktor Gyokeres",
  "Benjamin Sesko",
  "Dusan Vlahovic",
  "Aleksandar Mitrovic",
  "Hakan Calhanoglu",
  "Arda Guler",
  "Kenan Yildiz",
  "Cengiz Under",
  "Andriy Yarmolenko",
  "Mykhailo Mudryk",
  "Jonathan David",
  "Alphonso Davies",
  "Cyle Larin",
  "Tajon Buchanan",
  "Hirving Lozano",
  "Santiago Gimenez",
  "Raul Jimenez",
  "Alexis Vega",
  "Richarlison",
  "Paulo Dybala",
  "Nicolas Gonzalez",
  "Mateo Retegui",
  "Moise Kean",
  "Gianluca Scamacca",
  "Dusan Tadic",
  "Aleksandar Katai",
  "Orkun Kokcu",
  "Hamed Junior Traore",
  "Sebastiano Esposito",
  "Mehdi Taremi",
  "Sardar Azmoun",
  "Salem Al-Dawsari",
  "Akram Afif",
  "Marko Arnautovic",
  "Michael Gregoritsch",
  "Andrej Kramaric",
  "Ivan Perisic",
  "Abdallah Sima",
  "Nicolas Kuhn",
  "Youssef Msakni",
  "Wissam Ben Yedder",
  "Ousmane Dembele",
] as const;

const baseProbabilities = [
  15.4,
  13.3,
  7.7,
  6.7,
  5.9,
  4.8,
  4.8,
  3.8,
  3.8,
  3.8,
  3.8,
  3.5,
  3.3,
  3.2,
  3.1,
  3.0,
  2.9,
  2.8,
  2.7,
  2.6,
] as const;

export function getTopScorerProbability(rank: number) {
  if (rank < baseProbabilities.length) {
    return baseProbabilities[rank];
  }

  const probability = 2.5 - (rank - baseProbabilities.length) * 0.03;
  return Math.max(0.8, Math.round(probability * 10) / 10);
}